In [ ]:
# From state s, after playing action a, the probability of reaching state s'
transition_probabilities = [ # shape=[s, a, s']
[[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
[[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
[None, [0.8, 0.1, 0.1], None]]

# The corresponding reward, we will look up rewards[2][1][0] (which is +40)
rewards = [ # shape=[s, a, s']
[[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
[[0, 0, 0], [0, 0, 0], [0, 0, -50]],
[[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]

# To get the list of possible actions in s2, we will look up possible_actions[2] (in this case, only action a1 is possible)
# Possible actions in each state, indexed by state
possible_actions = [[0, 1, 2], [0, 2], [1]]

# Transition probability from s2 to s0 after playing action a1, we will look up transition_probabilities[2][1][0] (which is 0.8).
print("Transition probability from s2 to s0 after playing action a1: " + str(transition_probabilities[2][1][0])) # 0.8
# The corresponding reward, we will look up rewards[2][1][0] (which is +40)
print("Reward for transitioning from s2 to s0 after playing action a1: " + str(rewards[2][1][0])) # +40
# Possible actions in state s2
print("Possible actions in state s2: " + str(possible_actions[2])) # [1

Transition probability from s2 to s0 after playing action a1: 0.8
Reward for transitioning from s2 to s0 after playing action a1: 40
Possible actions in state s2: [1]


In [6]:
import numpy as np
# Initialize all the Q-Values to 0 (except for the the impossible actions, for which we set the Q-Values to –∞)
# Shape is [number of states, number of actions]
Q_values = np.full((3, 3), -np.inf)
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0

print("Initial Q-values:\n", Q_values)

Initial Q-values:
 [[  0.   0.   0.]
 [  0. -inf   0.]
 [-inf   0. -inf]]


In [ ]:
gamma = 0.9  # Discount factor

for iteration in range(50):
    Q_prev = Q_values.copy()
    for s in range(3):  # For each state
        for a in possible_actions[s]: # For each possible action in state s
            Q_values[s, a] = np.sum([
                transition_probabilities[s][a][sp] * (rewards[s][a][sp] +
                gamma * np.max(Q_prev[sp])) 
                for sp in range(3)])
            
    #print(f"Q-values after iteration {iteration + 1}:\n", Q_values)

print("Final Q-values after 50 iterations:\n", Q_values)
            
# For example, when the agent is in state s0 and it chooses action a1, the expected sum
# of discounted future rewards is approximately 17.0.


Final Q-values after 50 iterations:
 [[18.91891892 17.02702703 13.62162162]
 [ 0.                -inf -4.87971488]
 [       -inf 50.13365013        -inf]]


In [9]:
# For each state, let’s look at the action that has the highest Q-Value:
np.argmax(Q_values, axis=1)  # This will give us the best action for each state

array([0, 0, 1])

This gives us the optimal policy for this MDP, when using a discount factor of 0.90: 

in state s0 choose action a0; 

in state s1 choose action a0 (i.e., stay put); 

and in state s2 choose action a1 (the only possible action). 

Interestingly, if we increase the discount
factor to 0.95, the optimal policy changes: in state s1 the best action becomes a2 (go
through the fire!). This makes sense because the more you value future rewards, the
more you are willing to put up with some pain now for the promise of future bliss.